FROM maven:3.6.3-openjdk-11 as build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean install test

FROM openjdk:11-jre-slim
WORKDIR /app
COPY --from=build /app/target/accenture-techhub-0.0.1-SNAPSHOT.war .
CMD ["java", "-jar", "accenture-techhub-0.0.1-SNAPSHOT.war"]
